version: "3.9"

services:

  redis:
    image: redis:alpine
    networks:
      - frontend

  vote:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 5000:80
    networks:
      - frontend
    deploy:
      replicas: 2

networks:
  frontend:
